baseURL: https://dshah-wlw.github.io/
languageCode: en-us
title: dshah's site
theme: PaperModX

params:
# customisations
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  description: my site
  author:
    - dshah

# set up home info details
  homeInfoParams:
      Title: Hi there 👋
      Content: My name is dshah
      socialIcons:
      - name: github-simple
        url: "https://github.com/dshah-wlw"
      - name: linkedin-simple
        url: "https://linkedin.com/"
      - name: email
        url: "test@example.com"
# production so more features are enabled
  env: production

