baseURL: https://dshah-wlw.github.io/
languageCode: en-us
title: dshah's site
theme: PaperModX
params:
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  env: production
  description: my site
  author:
    - dshah
